### ISSUE TITLE
じぶんリリースノートにPixelaで歩数を出したい

### ISSUE THREAD

**Issue by mom0tomo** [mom0tomo/mom0tomo.github.io#15]
- Pixelaの草を「歩数:xxx歩」の下に埋め込みたい
- 毎日の歩数をPixelaに送る何らかの仕組みがほしい
  - LINEから操作できるのでLINEから送る?
  - IFTTTでうまくできるかも
     - https://qiita.com/kento-Y/items/2615577c56941e25e900#2-%E3%82%B7%E3%83%A7%E3%83%BC%E3%83%88%E3%82%AB%E3%83%83%E3%83%88%E8%B5%B7%E5%BA%8A%E6%99%82%E9%96%93%E3%81%A8%E7%9D%A1%E7%9C%A0%E6%99%82%E9%96%93%E3%82%92%E3%83%84%E3%82%A4%E3%83%BC%E3%83%88%E3%82%92%E4%BD%9C%E6%88%90%E3%81%99%E3%82%8B

**Comment by a-know** [comment]
わいわい、ありがとうございます！！
https://github.com/a-know/Pixela/wiki/Useful-case-examples にも「歩数」関連の事例が2つほどありますね 👀

**Comment by mom0tomo** [comment]
おお〜！！ありがとうございます！参考にします！

**Comment by mom0tomo** [comment]
- ~iOS ヘルスキットのAPIで歩数を取得~
  - curlで取得が難しそうだったのでやめた
- Oura RingのAPIで歩数を取得する
  - https://cloud.ouraring.com/v2/docs#tag/Daily-Activity
- Pixela に記録する
  - [pi](https://github.com/a-know/pi)でできる
  - https://blog.a-know.me/entry/2019/02/24/214142
- GitHubActionsで定期的に実行する
  - [この感じ](https://github.com/mom0tomo/mom0tomo.github.io/blob/main/.github/workflows/notify_long_time_no_see.yml)でできる

**Comment by mom0tomo** [comment]
https://github.com/mom0tomo/mom0tomo.github.io/pull/17
@a-know うまく実行できました！ 🎉

**Comment by a-know** [comment]
わー、おめでとうございます＆ご利用ありがとうございますっ 😊
